[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "2fyDo7MXWaRHn5pFanYxs2EenfbUkWrfJhDVzfmz6zvX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./target/deploy/crowdfunding-keypair.json/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
